Part 4 - Batches, Layers and Objects  
https://www.youtube.com/watch?v=TEWy9vZcxW4

In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [4]:
X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]
    ]

np.random.randn(no. of values in each nested list in x, no. of nested lists in x)  

In [13]:
class LayerDense:
    
    
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros(1, dtype=float, order='C')
    
    
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases 

In [8]:
print(0.1*np.random.randn(4, 3))
# multiply 0.1 to keep values between -1 and +1

[[ 0.22697546 -0.14543657  0.00457585]
 [-0.01871839  0.15327792  0.14693588]
 [ 0.01549474  0.03781625 -0.08877857]
 [-0.19807965 -0.03479121  0.0156349 ]]


Output from layer1 will be input for layer2  
i.e. layer1[1] = layer2[0]

In [14]:
layer1 = LayerDense(4, 5)
layer2 = LayerDense(5, 2)

In [15]:
layer1.forward(X)
print(layer1.output)

[[-0.52207269  0.29130278 -0.98958469  0.11538014 -0.10007759]
 [ 0.02234328 -0.16447685 -1.14624105  0.09143863 -0.54525363]
 [-0.65534102 -0.20335419 -0.57157038  0.08727088  0.28777291]]


In [16]:
np. __version__

'1.19.2'

In [17]:
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.14216652 -0.09398694]
 [ 0.05984339 -0.22289481]
 [ 0.17689072  0.02645529]]
